# Generated by Django 6.0.7 on 2026-08-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_submission'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('assignment', 'student'), name='unique_submission_per_student_assignment'),
        ),
    ]
